import api from './api';

export const erpApi = {
  materials: {
    listProducts: () => api.get('/materiais/produtos'),
    createProduct: (payload) => api.post('/materiais/produtos', payload),
    deleteProduct: (id) => api.delete(`/materiais/produtos/${id}`),
    listCompanies: () => api.get('/materiais/empresas'),
    createCompany: (payload) => api.post('/materiais/empresas', payload),
    deleteCompany: (id) => api.delete(`/materiais/empresas/${id}`),
    listCategories: () => api.get('/materiais/categorias'),
    createCategory: (payload) => api.post('/materiais/categorias', payload),
    deleteCategory: (id) => api.delete(`/materiais/categorias/${id}`),
    listWarehouses: () => api.get('/materiais/armazens'),
    createWarehouse: (payload) => api.post('/materiais/armazens', payload),
    deleteWarehouse: (id) => api.delete(`/materiais/armazens/${id}`),
  },
  financial: {
    listAccounts: () => api.get('/financeiro/contas'),
    createAccount: (payload) => api.post('/financeiro/contas', payload),
    deleteAccount: (id) => api.delete(`/financeiro/contas/${id}`),
    listStatements: () => api.get('/financeiro/extratos'),
    createStatement: (payload) => api.post('/financeiro/extratos', payload),
    deleteStatement: (id) => api.delete(`/financeiro/extratos/${id}`),
    listCashFlows: () => api.get('/financeiro/fluxo-caixa'),
    createCashFlow: (payload) => api.post('/financeiro/fluxo-caixa', payload),
    deleteCashFlow: (id) => api.delete(`/financeiro/fluxo-caixa/${id}`),
    listBudgets: () => api.get('/financeiro/orcamentos'),
    createBudget: (payload) => api.post('/financeiro/orcamentos', payload),
    deleteBudget: (id) => api.delete(`/financeiro/orcamentos/${id}`),
    listInvoices: () => api.get('/fiscal/notas-fiscais'),
    createInvoice: (payload) => api.post('/fiscal/notas-fiscais', payload),
    deleteInvoice: (id) => api.delete(`/fiscal/notas-fiscais/${id}`),
    listTaxes: () => api.get('/fiscal/impostos'),
    createTax: (payload) => api.post('/fiscal/impostos', payload),
    deleteTax: (id) => api.delete(`/fiscal/impostos/${id}`),
  },
  assets: {
    listAssets: () => api.get('/ativos'),
    createAsset: (payload) => api.post('/ativos/0', payload),
    deleteAsset: (id) => api.delete(`/ativos/${id}`),
    listCategories: () => api.get('/ativos/categorias'),
    createCategory: (payload) => api.post('/ativos/categorias', payload),
    deleteCategory: (id) => api.delete(`/ativos/categorias/${id}`),
    listLocations: () => api.get('/ativos/localizacoes'),
    createLocation: (payload) => api.post('/ativos/localizacoes/0', payload),
    deleteLocation: (id) => api.delete(`/ativos/localizacoes/${id}`),
  },
  hr: {
    listEmployees: () => api.get('/rh/colaboradores'),
    createEmployee: (payload) => api.post('/rh/colaboradores', payload),
    deleteEmployee: (id) => api.delete(`/rh/colaboradores/${id}`),
    listRoles: () => api.get('/rh/funcoes'),
    createRole: (payload) => api.post('/rh/funcoes', payload),
    deleteRole: (id) => api.delete(`/rh/funcoes/${id}`),
  },
  sales: {
    listClients: () => api.get('/vendas-compras/clientes'),
    createClient: (payload) => api.post('/vendas-compras/clientes', payload),
    deleteClient: (id) => api.delete(`/vendas-compras/clientes/${id}`),
    listSellers: () => api.get('/vendas-compras/vendedor'),
    createSeller: (payload) => api.post('/vendas-compras/vendedor', payload),
    deleteSeller: (id) => api.delete(`/vendas-compras/vendedor/${id}`),
    listContracts: () => api.get('/vendas-compras/contratos'),
    createContract: (payload) => api.post('/vendas-compras/contratos', payload),
    deleteContract: (id) => api.delete(`/vendas-compras/contratos/${id}`),
    listOrders: () => api.get('/vendas-compras/pedidos-venda'),
    createOrder: (payload) => api.post('/vendas-compras/pedidos-venda', payload),
    deleteOrder: (id) => api.delete(`/vendas-compras/pedidos-venda/${id}`),
  },
  bi: {
    listDashboards: () => api.get('/bi/dashboards'),
    createDashboard: (payload) => api.post('/bi/dashboards', payload),
    deleteDashboard: (id) => api.delete(`/bi/dashboards/${id}`),
    listKpis: () => api.get('/bi/kpis'),
    createKpi: (payload) => api.post('/bi/kpis', payload),
    deleteKpi: (id) => api.delete(`/bi/kpis/${id}`),
    listCaches: () => api.get('/bi/cache'),
    createCache: (payload) => api.post('/bi/cache', payload),
    deleteCache: (id) => api.delete(`/bi/cache/${id}`),
  },
};
